routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::resource('categories', 'CategoryController');
Route::get('/categories/{category}/delete', 'CategoryController@destroy')->name('categories.delete');
Route::resource('posts', 'PostController');
Route::post('/categories/comment', 'CategoryController@storeComment')->name('categories.storeComment');
Route::get('/posts/{post}/delete', 'PostController@destroy')->name('posts.delete');
Route::get('/posts/download-file/{filename}', 'PostController@downloadFile')->name('posts.downloadFile');
Route::post('/posts/comment', 'PostController@storeComment')->name('posts.storeComment');

app/Models/Db/Post.php
<?php

namespace App\Models\Db;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Class Post
 *
 * @property int id
 * @property string file
 * @property mixed comments
 * @package App\Models\Db
 * @method static paginate(?int $perPage = null)
 * @method static create(array $data)
 * @mixin \Eloquent
 */
class Post extends Model
{
    public const CONTENT_PREVIEW_STR_LIMIT = 200;

    public const STORE_PATH = 'files';

    public const MAX_FILE_SIZE_KB = 2048;

    /**
     * @var array
     */
    protected $fillable = [
        'category_id',
        'name',
        'content',
        'file',
    ];

    /**
     * Relation to comments
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(PostComment::class);
    }

    /**
     * Relation to category
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Post\CreateCommentRequest;
use App\Http\Requests\Post\CreateUpdateRequest;
use App\Models\Db\Post;
use App\Models\Db\PostComment;
use App\Services\Category\CategoryService;
use App\Services\Post\PostService;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use PageMeta;
use Session;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

/**
 * Class PostController
 * @package App\Http\Controllers
 */
class PostController extends Controller
{
    /**
     * @var PostService
     */
    protected $postService;

    /**
     * @var CategoryService
     */
    protected $categoryService;

    /**
     * PostController constructor.
     * @param PostService $postService
     * @param CategoryService $categoryService
     */
    public function __construct(PostService $postService, CategoryService $categoryService)
    {
        $this->postService = $postService;
        $this->categoryService = $categoryService;
    }

    /**
     * Display a listing of posts.
     * @return View
     */
    public function index(): View
    {
        PageMeta::setTitle(__('post.posts'));

        return view('post.index', [
            'posts' => $this->postService->getPaginated()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     * @return View
     */
    public function create(): View
    {
        PageMeta::setTitle(__('post.create.title'));
        Session::put(self::REDIRECT_TO, redirect()->back()->getTargetUrl());

        return view('post.create', [
            'post' => new Post(),
            'categories' => $this->categoryService->getAllForSelect(),
        ]);
    }

    /**
     * Store a newly created post in storage.
     * @param CreateUpdateRequest $request
     * @return array
     */
    public function store(CreateUpdateRequest $request): array
    {
        $this->postService->create(array_merge(
            $request->except(['_token', 'file']),
            ['file' => $this->postService->storeFileFromRequest($request)]
        ));
        $request->session()->flash('success-title', __('common.messages.create.success.title'));
        $request->session()->flash('success', __('post.messages.create.success'));

        return ['redirect' => Session::pull(self::REDIRECT_TO)];
    }

    /**
     * Display the specified post.
     * @param Post $post
     * @return \Illuminate\Contracts\View\Factory|View
     */
    public function show(Post $post): View
    {
        return view('post.show', [
            'post' => $post,
            'comments' => $post->comments,
            'comment' => new PostComment()
        ]);
    }

    /**
     * Show the form for editing the specified post.
     * @param Post $post
     * @return View
     */
    public function edit(Post $post): View
    {
        Session::put(self::REDIRECT_TO, redirect()->back()->getTargetUrl());

        return view('post.edit', [
            'post' => $post,
            'categories' => $this->categoryService->getAllForSelect(),
        ]);
    }

    /**
     * Update the specified post in storage.
     * @param CreateUpdateRequest $request
     * @param Post $post
     * @return array
     */
    public function update(CreateUpdateRequest $request, Post $post): array
    {
        $this->postService->update(array_merge(
            $request->except(['_token', 'file']),
            ['file' => $this->postService->storeFileFromRequest($request)]
        ), $post);

        $request->session()->flash('success-title', __('common.messages.update.success.title'));
        $request->session()->flash('success', __('post.messages.update.success'));

        return ['redirect' => Session::pull(self::REDIRECT_TO)];
    }

    /**
     * Remove the specified category from storage.
     * @param Post $post
     * @throws \Exception
     * @return RedirectResponse
     */
    public function destroy(Post $post): RedirectResponse
    {
        $post->delete();

        return redirect()->back()->with('success', __('post.messages.delete.success'))
            ->with('success-title', __('common.messages.delete.success.title'));
    }

    /**
     * Download file
     * @param string $filename
     * @return BinaryFileResponse
     */
    public function downloadFile(string $filename): BinaryFileResponse
    {
        return response()->download(storage_path('app') . '/'.Post::STORE_PATH.'/'.$filename);
    }

    /**
     * Create comment for post
     * @param CreateCommentRequest $request
     * @return array
     */
    public function storeComment(CreateCommentRequest $request): array
    {
        return ['comment' => $this->postService->createComment($request->except('_token'))];
    }
}

resources/views/post/create.blade.php
@extends('layout')

@section('main')
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @include('post.forms.edit', [
                        'url' => route('posts.store'),
                        'method' => 'post'
                    ])
                    <br>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/post/edit.blade.php
@extends('layout')

@section('main')
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @include('post.forms.edit', [
                        'url' => route('posts.update', $post->id),
                        'method' => 'put'
                    ])
                    <br>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/post/index.blade.php
@extends('layout')

@section('main')
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @include('common.partials.messages')
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="clearfix">
                        <div class="float-left">
                            <a href="{{ route('posts.create') }}" class="btn btn-primary">
                                {{ __('post.index.add') }}
                            </a>
                        </div>
                        <div class="float-right">
                            <a href="{{ route('categories.index') }}" class="btn btn-secondary">
                                {{ __('category.categories') }}
                            </a>
                        </div>
                    </div>
                    <br>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="alert alert-primary" role="alert" @if(count($posts)) style="display: none;" @endif>
                        {{ __('post.index.no_posts') }}
                    </div>
                    @if(count($posts))
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">{{ __('form/attributes.name') }}</th>
                                <th scope="col">{{ __('form/attributes.content') }}</th>
                                <th scope="col">{{ __('form/attributes.category_id') }}</th>
                                <th scope="col">{{ __('form/attributes.file') }}</th>
                                <th scope="col" width="20%"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($posts as $post)
                                <tr>
                                    <td>{{ $post->name }}</td>
                                    <td>
                                        {{ str_limit($post->content, \App\Models\Db\Post::CONTENT_PREVIEW_STR_LIMIT) }}
                                    </td>
                                    <td>{{ $post->category->name }}</td>
                                    <td>
                                        @if ($post->file)
                                            <a href="{{ route('posts.downloadFile', basename($post->file)) }}">
                                                {{ __('post.index.download') }}
                                            </a>
                                        @else
                                            {{ __('post.index.no_file') }}
                                        @endif
                                    </td>
                                    <td>
                                        <div>
                                            <a href="{{ route('posts.show', $post->id) }}" class="btn btn-primary">
                                                {{ __('common.form.show') }}
                                            </a>
                                        </div>
                                        <br>
                                        <div>
                                            <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-primary">
                                                {{ __('common.form.edit') }}
                                            </a>
                                        </div>
                                        <br>
                                        <div>
                                            <a href="{{ route('posts.delete', $post->id) }}" class="btn btn-danger">
                                                {{ __('common.form.delete') }}
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @endif
                    <br>
                    <div>
                        {!! $posts->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/post/show.blade.php
@extends('layout')

@section('main')
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @include('common.partials.messages')
                </div>
            </div>
            @include('common.partials.inlineMenu')
            <div class="row">
                <div class="col-lg-12">
                    <h1>{{ $post->name }}</h1>
                    <p>{{ $post->created_at->format('d.m.Y, H:i') }}</p>
                    <div>
                        {!! $post->content !!}
                    </div>
                    <div class="mt-5">
                        <h4>{{ __('common.comments.section_title') }}</h4>
                        <div class="mb-5 mt-4" id="comments">
                            @if(count($comments))
                                @foreach($comments as $postComment)
                                    <div class="mb-4">
                                        <p><b>{{ $postComment->author }}</b></p>
                                        <p>{{ $postComment->content }}</p>
                                    </div>
                                @endforeach
                            @else
                                <div class="no-items">{{ __('common.comments.no_comments') }}</div>
                            @endif
                        </div>
                    </div>
                    <div class="mt-5">
                        <div class="mb-4">
                            <h4>{{ __('common.comments.add') }}</h4>
                        </div>
                        @include('post.forms.comment')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection