routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::resource('categories', 'CategoryController');
Route::get('/categories/{category}/delete', 'CategoryController@destroy')->name('categories.delete');
Route::resource('posts', 'PostController');
Route::post('/categories/comment', 'CategoryController@storeComment')->name('categories.storeComment');
Route::get('/posts/{post}/delete', 'PostController@destroy')->name('posts.delete');
Route::get('/posts/download-file/{filename}', 'PostController@downloadFile')->name('posts.downloadFile');
Route::post('/posts/comment', 'PostController@storeComment')->name('posts.storeComment');

app/Models/Db/Category.php
<?php

namespace App\Models\Db;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Class Category
 *
 * @property int id
 * @property mixed comments
 * @property mixed posts
 * @package App\Models\Db
 * @method static paginate(?int $perPage)
 * @method static create(array $data)
 * @mixin \Eloquent
 */
class Category extends Model
{
    /**
     * @var bool
     */
    public $timestamps = false;

    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
    ];

    /**
     * Relation to comments
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(CategoryComment::class);
    }

    /**
     * Relation to posts
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Category\CreateCommentRequest;
use App\Http\Requests\Category\CreateUpdateRequest;
use App\Models\Db\Category;
use App\Models\Db\CategoryComment;
use App\Services\Category\CategoryService;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use PageMeta;
use Session;

/**
 * Class CategoryController
 * @package App\Http\Controllers
 */
class CategoryController extends Controller
{
    /**
     * @var CategoryService
     */
    protected $categoryService;

    /**
     * CategoryController constructor.
     * @param CategoryService $categoryService
     */
    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    /**
     * Display a listing of categories.
     * @return View
     */
    public function index(): View
    {
        PageMeta::setTitle(__('category.categories'));

        return view('category.index', [
            'categories' => $this->categoryService->getPaginated()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     * @return View
     */
    public function create(): View
    {
        PageMeta::setTitle(__('category.create.title'));
        Session::put(self::REDIRECT_TO, redirect()->back()->getTargetUrl());

        return view('category.create', [
            'category' => new Category(),
        ]);
    }

    /**
     * Store a newly created category in storage.
     * @param CreateUpdateRequest $request
     * @return array
     */
    public function store(CreateUpdateRequest $request): array
    {
        $this->categoryService->create($request->except('_token'));
        $request->session()->flash('success-title', __('common.messages.create.success.title'));
        $request->session()->flash('success', __('category.messages.create.success'));

        return ['redirect' => Session::pull(self::REDIRECT_TO)];
    }

    /**
     * Display the specified category.
     * @param Category $category
     * @return \Illuminate\Contracts\View\Factory|View
     */
    public function show(Category $category): View
    {
        return view('category.show', [
            'category' => $category,
            'posts' => $category->posts()->paginate(),
            'comments' => $category->comments,
            'comment' => new CategoryComment()
        ]);
    }

    /**
     * Show the form for editing the specified category.
     * @param Category $category
     * @return View
     */
    public function edit(Category $category): View
    {
        Session::put(self::REDIRECT_TO, redirect()->back()->getTargetUrl());

        return view('category.edit', [
            'category' => $category,
        ]);
    }

    /**
     * Update the specified category in storage.
     * @param CreateUpdateRequest $request
     * @param Category $category
     * @return array
     */
    public function update(CreateUpdateRequest $request, Category $category): array
    {
        $category->update($request->except('_token'));
        $request->session()->flash('success-title', __('common.messages.update.success.title'));
        $request->session()->flash('success', __('category.messages.update.success'));

        return ['redirect' => Session::pull(self::REDIRECT_TO)];
    }

    /**
     * Remove the specified category from storage.
     * @param Category $category
     * @throws \Exception
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Category $category): RedirectResponse
    {
        $category->delete();

        return redirect()->back()->with('success', __('category.messages.delete.success'))
            ->with('success-title', __('common.messages.delete.success.title'));
    }

    /**
     * Create comment for category
     * @param CreateCommentRequest $request
     * @return array
     */
    public function storeComment(CreateCommentRequest $request): array
    {
        return ['comment' => $this->categoryService->createComment($request->except('_token'))];
    }
}

resources/views/category/create.blade.php
@extends('layout')

@section('main')
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @include('category.forms.edit', [
                        'url' => route('categories.store'),
                        'method' => 'post'
                    ])
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layout')

@section('main')
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @include('category.forms.edit', [
                        'url' => route('categories.update', $category->id),
                        'method' => 'put'
                    ])
                    <br>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layout')

@section('main')
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @include('common.partials.messages')
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="clearfix">
                        <div class="float-left">
                            <a href="{{ route('categories.create') }}" class="btn btn-primary">
                                {{ __('category.index.add') }}
                            </a>
                        </div>
                        <div class="float-right">
                            <a href="{{ route('posts.index') }}" class="btn btn-secondary">
                                {{ __('post.posts') }}
                            </a>
                        </div>
                    </div>
                    <br>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="alert alert-primary" role="alert" @if(count($categories)) style="display: none;" @endif>
                        {{ __('category.index.no_categories') }}
                    </div>
                    @if(count($categories))
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">{{ __('category.form.name') }}</th>
                                <th scope="col">{{ __('category.form.description') }}</th>
                                <th scope="col" width="20%"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ $category->description }}</td>
                                    <td>
                                        <div>
                                            <a href="{{ route('categories.show', $category->id) }}" class="btn btn-primary">
                                                {{ __('common.form.show') }}
                                            </a>
                                        </div>
                                        <br>
                                        <div>
                                            <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-primary">
                                                {{ __('common.form.edit') }}
                                            </a>
                                        </div>
                                        <br>
                                        <div>
                                            <a href="{{ route('categories.delete', $category->id) }}" class="btn btn-danger">
                                                {{ __('common.form.delete') }}
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @endif
                    <br>
                    <div>
                        {!! $categories->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/show.blade.php
@extends('layout')

@section('main')
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    @include('common.partials.messages')
                </div>
            </div>
            @include('common.partials.inlineMenu')
            <div class="row">
                <div class="col-lg-12">
                    <h1>{{ $category->name }}</h1>
                    <div class="mt-5">
                        <div class="alert alert-primary" role="alert" @if(count($posts)) style="display: none;" @endif>
                            {{ __('post.index.no_posts') }}
                        </div>
                        @if(count($posts))
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col">{{ __('form/attributes.name') }}</th>
                                    <th scope="col">{{ __('form/attributes.content') }}</th>
                                    <th scope="col">{{ __('form/attributes.file') }}</th>
                                    <th scope="col" width="20%"></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($posts as $post)
                                    <tr>
                                        <td>{{ $post->name }}</td>
                                        <td>
                                            {{ str_limit($post->content, \App\Models\Db\Post::CONTENT_PREVIEW_STR_LIMIT) }}
                                        </td>
                                        <td>
                                            @if ($post->file)
                                                <a href="{{ route('posts.downloadFile', basename($post->file)) }}">
                                                    {{ __('post.index.download') }}
                                                </a>
                                            @else
                                                {{ __('post.index.no_file') }}
                                            @endif
                                        </td>
                                        <td>
                                            <div>
                                                <a href="{{ route('posts.show', $post->id) }}" class="btn btn-primary">
                                                    {{ __('common.form.show') }}
                                                </a>
                                            </div>
                                            <br>
                                            <div>
                                                <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-primary">
                                                    {{ __('common.form.edit') }}
                                                </a>
                                            </div>
                                            <br>
                                            <div>
                                                <a href="{{ route('posts.delete', $post->id) }}" class="btn btn-danger">
                                                    {{ __('common.form.delete') }}
                                                </a>
                                            </div>
                                         </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <br>
                            <div>
                                {!! $posts->render() !!}
                            </div>
                        @endif
                    </div>
                    <div class="mt-5">
                        <h4>{{ __('common.comments.section_title') }}</h4>
                        <div class="mb-5 mt-4" id="comments">
                            @if(count($comments))
                                @foreach($comments as $categoryComment)
                                    <div class="mb-4">
                                        <p><b>{{ $categoryComment->author }}</b></p>
                                        <p>{{ $categoryComment->content }}</p>
                                    </div>
                                @endforeach
                            @else
                                <div class="no-items">{{ __('common.comments.no_comments') }}</div>
                            @endif
                        </div>
                    </div>
                    <div class="mt-5">
                        <div class="mb-4">
                            <h4>{{ __('common.comments.add') }}</h4>
                        </div>
                        @include('category.forms.comment')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection